#pragma once

#include "assets/api/mesh_data.h"

#include "assets/xxd_mesh/ball_mesh.h"
#include "assets/xxd_mesh/lane_mesh.h"
#include "assets/xxd_mesh/pin_mesh.h"
#include "assets/xxd_mesh/star_mesh.h"
#include "assets/xxd_mesh/gem_mesh.h"
#include "assets/xxd_mesh/cannon_mesh.h"
#include "assets/xxd_mesh/chest_mesh.h"
#include "assets/xxd_mesh/chest_anim.h"
#include "assets/xxd_mesh/angel_mesh.h"
#include "assets/xxd_mesh/angel_anim.h"
#include "assets/xxd_mesh/cherub_mesh.h"
#include "assets/xxd_mesh/cherub_anim.h"
#include "assets/xxd_mesh/seraph_mesh.h"
#include "assets/xxd_mesh/seraph_anim.h"
#include "assets/xxd_mesh/throne_mesh.h"
#include "assets/xxd_mesh/throne_anim.h"
