VERSION_SCRIPT := $(PWD)/scripts/increment_build_version.sh
VERSION_HEADER := $(PWD)/build/generated/build_version.h

FORCE:

$(VERSION_HEADER): FORCE $(VERSION_SCRIPT)
	@bash $(VERSION_SCRIPT)

SYSROOT=iphoneos
#SYSROOT=iphonesimulator
sdl2:
	#-DCMAKE_OSX_SYSROOT=iphoneos \
	rm -rf build/ios/sdl2
	mkdir -p build/ios/sdl2
	cd build/ios/sdl2 && \
	cmake \
		-G "Unix Makefiles" \
		-DCMAKE_SYSTEM_NAME=iOS \
        -DCMAKE_OSX_SYSROOT=$(SYSROOT) \
		-DCMAKE_OSX_ARCHITECTURES=arm64 \
		-DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
		-DCMAKE_INSTALL_PREFIX=$(PWD)/build/ios/usr \
		-DSDL_SHARED=OFF \
		-DSDL_STATIC=ON \
		-DSDL_TEST=OFF \
		$(PWD)/3rdparty/SDL && \
	make -j && \
	make install

JOLT_SRC_DIR=$(PWD)/3rdparty/JoltPhysics
JOLT_BUILD_DIR=build/ios/jolt

jolt:
	rm -rf $(JOLT_BUILD_DIR)/../usr/lib/libJolt* $(JOLT_BUILD_DIR)
	mkdir -p $(JOLT_BUILD_DIR)
	(cd $(JOLT_BUILD_DIR) && \
	cmake \
		-DCMAKE_SYSTEM_NAME=iOS \
        -DCMAKE_OSX_SYSROOT=$(SYSROOT) \
		-DCMAKE_OSX_ARCHITECTURES=arm64 \
		-DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
		-DENABLE_BITCODE=OFF \
		-DUSE_ASSERTS=ON \
		-DTARGET_SAMPLES=OFF \
		-DTARGET_UNIT_TESTS=OFF \
		-DTARGET_VIEWER=OFF \
		-DCPP_EXCEPTIONS_ENABLED=OFF \
		-DCPP_RTTI_ENABLED=OFF \
		-DBUILD_SHARED_LIBS=OFF \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=$(abspath $(JOLT_BUILD_DIR)/../usr/lib) \
		$(abspath $(JOLT_SRC_DIR))/Build && \
	cmake --build . --config Release --parallel)
