#pragma once

#include <SDL.h>

#include "./../eggsfm/xfm_api.h"
#include "./../eggsfm/xfm_impl.cpp"
#include "./clayton/soundsettings.h"
#include <SDL.h>
#include <cstdio>
#include <cstring>

/* clang-format off */
constexpr xfm_patch_opn PATCH_00 =
{
    .ALG = 2,
    .FB  = 5,
    .AMS = 0,
    .FMS = 0,

    .op =
    {
        { .DT = 1, .MUL = 3, .TL = 38, .RS = 0, .AR = 12, .AM = 0, .DR = 7, .SR = 11, .SL = 4, .RR = 6, .SSG = 0 },
        { .DT = -1, .MUL = 1, .TL = 38, .RS = 0, .AR = 17, .AM = 0, .DR = 5, .SR = 2, .SL = 2, .RR = 1, .SSG = 0 },
        { .DT = 1, .MUL = 2, .TL = 5,  .RS = 0, .AR = 11, .AM = 0, .DR = 13, .SR = 11, .SL = 5, .RR = 13, .SSG = 0 },
        { .DT = -1, .MUL = 1, .TL = 0,  .RS = 0, .AR = 31, .AM = 0, .DR = 9,  .SR = 15, .SL = 5, .RR = 8,  .SSG = 3 }
    }
};

constexpr xfm_patch_opn PATCH_01 =
{
    .ALG = 4,
    .FB  = 6,
    .AMS = 0,
    .FMS = 0,
    .op =
    {
        { .DT = 0, .MUL = 3, .TL = 35, .RS = 0, .AR = 13, .AM = 0, .DR = 1,  .SR = 25, .SL = 2, .RR = 0, .SSG = 0 },
        { .DT = 0, .MUL = 1, .TL = 20, .RS = 0, .AR = 17, .AM = 0, .DR = 10, .SR = 8,  .SL = 2, .RR = 7, .SSG = 0 },
        { .DT = 0, .MUL = 1, .TL = 11, .RS = 0, .AR = 8,  .AM = 0, .DR = 4,  .SR = 23, .SL = 7, .RR = 1, .SSG = 0 },
        { .DT = 0, .MUL = 1, .TL = 14, .RS = 0, .AR = 25, .AM = 0, .DR = 0,  .SR = 10, .SL = 0, .RR = 9, .SSG = 0 }
    }
};

// Hi-hat patch (for channel 2)
constexpr xfm_patch_opn PATCH_02 =
{
    .ALG = 7,
    .FB  = 7,
    .AMS = 0,
    .FMS = 0,
    .op =
    {
        { .DT = 3, .MUL = 13, .TL =  8, .RS = 3, .AR = 31, .AM = 0, .DR = 31, .SR =  0, .SL = 15, .RR = 15, .SSG = 0 },
        { .DT = 2, .MUL = 11, .TL = 12, .RS = 3, .AR = 31, .AM = 0, .DR = 31, .SR =  0, .SL = 15, .RR = 15, .SSG = 0 },
        { .DT = 1, .MUL =  7, .TL = 16, .RS = 3, .AR = 31, .AM = 0, .DR = 30, .SR =  0, .SL = 15, .RR = 14, .SSG = 0 },
        { .DT = 0, .MUL = 15, .TL = 20, .RS = 3, .AR = 31, .AM = 0, .DR = 29, .SR =  0, .SL = 15, .RR = 13, .SSG = 0 }
    }
};
/* clang-format on */

struct GameSoundSystem
{
    // ------------------------------------------------------------------------
    // SFX identifiers
    // ------------------------------------------------------------------------
    enum SfxId
    {
        SFX_BALL_HIT_LANE = 0,
        SFX_BALL_HIT_PINS,
        SFX_PIN_HIT_PIN,
        SFX_SCORE_DISPLAY,
        SFX_GUTTER,
        SFX_TIMEOUT
    };

    // ------------------------------------------------------------------------
    // Modules
    // ------------------------------------------------------------------------

    xfm_module* musicModule = nullptr;
    xfm_module* sfxModule   = nullptr;

    SDL_AudioDeviceID audioDev = 0;

    float musicVolume = 1.0f;
    float sfxVolume   = 0.3f;
    int sampleRate = 44100;
    bool useWavPlayback = false;

    // Current song index (for switching between songs)
    int currentSongIndex = 1;

    // Sound settings UI
    SoundSettings settings;

    // ------------------------------------------------------------------------
    // Song patterns
    // ------------------------------------------------------------------------

    static const char* SONG1;
    static const char* SONG2;
    static const char* SONG3;
    static const char* SONG4;

    static constexpr const char* PAT_BALL_HIT_LANE = "4\n"
                                                     "C-3007F\n"
                                                     ".......\n"
                                                     "OFF....\n"
                                                     ".......\n";

    static constexpr const char* PAT_BALL_HIT_PINS = "6\n"
                                                     "C-3007F\n"
                                                     "E-3007F\n"
                                                     "G-3007F\n"
                                                     "OFF....\n"
                                                     ".......\n"
                                                     ".......\n";

    static constexpr const char* PAT_PIN_HIT_PIN = "4\n"
                                                   "A-3007F\n"
                                                   "OFF....\n"
                                                   ".......\n"
                                                   ".......\n";

    static constexpr const char* PAT_SCORE_DISPLAY = "8\n"
                                                     "C-3007F\n"
                                                     "E-3007F\n"
                                                     "G-3007F\n"
                                                     "C-4007F\n"
                                                     "OFF....\n"
                                                     ".......\n"
                                                     ".......\n"
                                                     ".......\n";

    static constexpr const char* PAT_GUTTER = "8\n"
                                              "A-2007F\n"
                                              "F-2007F\n"
                                              "D-2007F\n"
                                              "OFF....\n"
                                              ".......\n"
                                              ".......\n"
                                              ".......\n"
                                              ".......\n";

    static constexpr const char* PAT_TIMEOUT = "6\n"
                                               "D-4007F\n"
                                               "OFF....\n"
                                               "A-3007F\n"
                                               "OFF....\n"
                                               ".......\n"
                                               ".......\n";

    // ------------------------------------------------------------------------
    // Audio callback (mix both modules)
    // ------------------------------------------------------------------------

    static void audio_callback(void* userdata, Uint8* stream, int len)
    {
        GameSoundSystem* self = (GameSoundSystem*)userdata;

        // Safety check - if modules are null, just output silence
        if (!self->musicModule && !self->sfxModule) {
            std::memset(stream, 0, len);
            return;
        }

        int16_t* out = (int16_t*)stream;

        // len is in bytes. For stereo 16-bit audio:
        // 1 sample = 2 bytes
        // 1 frame (L + R) = 4 bytes
        // So number of frames = total bytes / 4
        int frames = len / 4;

        // Clear output buffer
        std::memset(out, 0, len);

        // Mix music (song only - more efficient!)
        if (self->musicModule)
            xfm_mix_song(self->musicModule, out, frames);

        // Mix SFX into temp buffer then add (SFX only - more efficient!)
        if (self->sfxModule)
        {
            static int16_t sfxBuf[4096 * 2];  // enough for your buffer size

            std::memset(sfxBuf, 0, sizeof(sfxBuf));
            xfm_mix_sfx(self->sfxModule, sfxBuf, frames);

            for (int i = 0; i < frames * 2; i++)
            {
                int32_t mixed = (int32_t)out[i] + sfxBuf[i];
                if (mixed > 32767) mixed = 32767;
                if (mixed < -32768) mixed = -32768;
                out[i] = (int16_t)mixed;
            }
        }
    }

    // ------------------------------------------------------------------------
    // Init
    // ------------------------------------------------------------------------

    bool initSoundSystem(const char* songPattern)
    {
        SDL_AudioSpec desired{};
        // Use the sampleRate setting (44100 for HiFi, 11025 for LoFi)
        desired.freq     = useWavPlayback ? 44100 : sampleRate;
        desired.format   = AUDIO_S16SYS;
        desired.channels = 2;
        desired.samples  = 256;
        desired.callback = audio_callback;
        desired.userdata = this;

        SDL_AudioSpec obtained{};

        audioDev = SDL_OpenAudioDevice(nullptr, 0, &desired, &obtained, 0);
        if (!audioDev)
        {
            printf("Audio error: %s\n", SDL_GetError());
            return false;
        }

        // Safety check - obtained.freq must be valid
        if (obtained.freq <= 0) {
            printf("Audio error: invalid sample rate %d\n", obtained.freq);
            SDL_CloseAudioDevice(audioDev);
            audioDev = 0;
            return false;
        }

        printf("Audio: %d Hz, %d samples (%.1f ms latency)\n",
               obtained.freq, obtained.samples,
               obtained.samples * 1000.0 / obtained.freq);

        // Create modules with the obtained sample rate
        musicModule = xfm_module_create(obtained.freq, obtained.samples, XFM_CHIP_YM3438);
        sfxModule   = xfm_module_create(obtained.freq, obtained.samples, XFM_CHIP_YM3438);

        if (!musicModule || !sfxModule)
        {
            printf("xfm_module_create failed\n");
            return false;
        }

        // --------------------------------------------------------------------
        // Load patches (use XFM_CHIP_YM3438 to match module creation)
        // --------------------------------------------------------------------

        xfm_patch_set(musicModule, 0x00, &PATCH_00, sizeof(PATCH_00), XFM_CHIP_YM3438);
        xfm_patch_set(musicModule, 0x01, &PATCH_01, sizeof(PATCH_01), XFM_CHIP_YM3438);
        xfm_patch_set(musicModule, 0x02, &PATCH_02, sizeof(PATCH_02), XFM_CHIP_YM3438);  // Hi-hat channel

        // reuse for SFX
        xfm_patch_set(sfxModule, 0x00, &PATCH_00, sizeof(PATCH_00), XFM_CHIP_YM3438);
        xfm_patch_set(sfxModule, 0x01, &PATCH_01, sizeof(PATCH_01), XFM_CHIP_YM3438);
        xfm_patch_set(sfxModule, 0x02, &PATCH_02, sizeof(PATCH_02), XFM_CHIP_YM3438);

        // --------------------------------------------------------------------
        // Declare song
        // --------------------------------------------------------------------

        printf("Declaring song...\n");
        xfm_song_declare(musicModule, 1, songPattern, 60, 6);
        printf("Playing song...\n");
        xfm_song_play(musicModule, 1, true);
        printf("Music should be playing!\n");

        // --------------------------------------------------------------------
        // Declare SFX (patterns now use instrument 00)
        // --------------------------------------------------------------------

        xfm_sfx_declare(sfxModule, SFX_BALL_HIT_LANE,   PAT_BALL_HIT_LANE,   60, 3);
        xfm_sfx_declare(sfxModule, SFX_BALL_HIT_PINS,   PAT_BALL_HIT_PINS,   60, 3);
        xfm_sfx_declare(sfxModule, SFX_PIN_HIT_PIN,     PAT_PIN_HIT_PIN,     60, 3);
        xfm_sfx_declare(sfxModule, SFX_SCORE_DISPLAY,   PAT_SCORE_DISPLAY,   60, 3);
        xfm_sfx_declare(sfxModule, SFX_GUTTER,          PAT_GUTTER,          60, 3);
        xfm_sfx_declare(sfxModule, SFX_TIMEOUT,         PAT_TIMEOUT,         60, 3);

        // --------------------------------------------------------------------
        // Volume
        // --------------------------------------------------------------------

        xfm_module_set_volume(musicModule, musicVolume);
        xfm_module_set_volume(sfxModule, sfxVolume);

        // Initialize sound settings UI
        initSoundSettings(&settings, this);

        SDL_PauseAudioDevice(audioDev, 0);

        return true;
    }

    // ------------------------------------------------------------------------
    // Shutdown
    // ------------------------------------------------------------------------

    void shutdown()
    {
        // Pause audio first
        if (audioDev) {
            SDL_PauseAudioDevice(audioDev, 1);
        }

        if (audioDev)
        {
            SDL_CloseAudioDevice(audioDev);
            audioDev = 0;
        }

        if (musicModule)
        {
            xfm_module_destroy(musicModule);
            musicModule = nullptr;
        }

        if (sfxModule)
        {
            xfm_module_destroy(sfxModule);
            sfxModule = nullptr;
        }
    }

    // ------------------------------------------------------------------------
    // Restart sound system (for quality changes)
    // ------------------------------------------------------------------------

    bool restartSoundSystem()
    {
        // Pause audio device first to prevent callback during restart
        if (audioDev) {
            SDL_PauseAudioDevice(audioDev, 1);
        }

        // Wait for any pending callbacks to finish
        SDL_Delay(100);

        // Shutdown current audio
        shutdown();

        // Small delay after shutdown
        SDL_Delay(50);

        // Re-init with new settings
        const char* songPattern = nullptr;
        switch (currentSongIndex) {
            case 1: songPattern = SONG1; break;
            case 2: songPattern = SONG2; break;
            case 3: songPattern = SONG3; break;
            case 4: songPattern = SONG4; break;
            default: songPattern = SONG1; break;
        }

        bool result = initSoundSystem(songPattern);

        // Audio device is unpaused by initSoundSystem
        return result;
    }

    // ------------------------------------------------------------------------
    // Next song
    // ------------------------------------------------------------------------

    void nextSong()
    {
        // Cycle through songs 1 -> 2 -> 3 -> 4 -> 1
        currentSongIndex = (currentSongIndex % 4) + 1;

        const char* songPattern = nullptr;
        switch (currentSongIndex) {
            case 1: songPattern = SONG1; break;
            case 2: songPattern = SONG2; break;
            case 3: songPattern = SONG3; break;
            case 4: songPattern = SONG4; break;
        }

        if (musicModule && songPattern) {
            // Declare and play new song (this replaces the current one)
            xfm_song_declare(musicModule, currentSongIndex, songPattern, 60, 6);
            xfm_song_play(musicModule, currentSongIndex, true);
            printf("Playing song %d\n", currentSongIndex);
        }
    }

    // ------------------------------------------------------------------------
    // SFX playback
    // ------------------------------------------------------------------------

    void playSfx(int id, int priority)
    {
        if (!sfxModule) return;

        SDL_LockAudioDevice(audioDev);
        xfm_sfx_play(sfxModule, id, priority);
        SDL_UnlockAudioDevice(audioDev);
    }

    // ------------------------------------------------------------------------
    // Game hooks
    // ------------------------------------------------------------------------

    void playSfxBallHitLane()        { playSfx(SFX_BALL_HIT_LANE, 3); }
    void playSfxBallHitPins()        { playSfx(SFX_BALL_HIT_PINS, 5); }
    void playSfxPinHitsAnotherPin()  { playSfx(SFX_PIN_HIT_PIN, 3); }
    void playSfxFinalScoreDisplayed(){ playSfx(SFX_SCORE_DISPLAY, 6); }
    void playSfxBallInGutter()       { playSfx(SFX_GUTTER, 5); }
    void playSfxBallTimeout()        { playSfx(SFX_TIMEOUT, 4); }

    // ------------------------------------------------------------------------
    // Volume
    // ------------------------------------------------------------------------

    void setMusicVolume(float v)
    {
        musicVolume = v;
        if (musicModule) xfm_module_set_volume(musicModule, v);
    }

    void setSfxVolume(float v)
    {
        sfxVolume = v;
        if (sfxModule) xfm_module_set_volume(sfxModule, v);
    }
    
    // ------------------------------------------------------------------------
    // Sound Settings UI
    // ------------------------------------------------------------------------
    
    void showSoundSettings()
    {
        settings.activated = true;
    }
    
    void hideSoundSettings()
    {
        settings.activated = false;
    }
    
    // bool processSoundSettingsEvent(SDL_Event event)
    // {
    //     return ::processSoundSettingsEvent(&settings, event);
    // }

    // void buildSoundSettingsClay()
    // {
    //     buildSoundSettingsClay(&settings);
    // }
};

// -----------------------------------------------------------------------------
// SoundSettings function implementations (must be after GameSoundSystem is defined)
// -----------------------------------------------------------------------------

inline void initSoundSettings(SoundSettings* self, GameSoundSystem* soundSystem)
{
    self->soundSystem = soundSystem;
    self->activated = false;

    // Initialize from sound system
    self->musicVolume = soundSystem->musicVolume;
    self->sfxVolume = soundSystem->sfxVolume;
    self->quality = soundSystem->useWavPlayback ? SoundSettings::QUALITY_WAV :
                    (soundSystem->sampleRate == 44100 ? SoundSettings::QUALITY_HIFI : SoundSettings::QUALITY_LOFI);

    // Volume labels
    strcpy(self->musicVolLabels[0], "0%");
    strcpy(self->musicVolLabels[1], "25%");
    strcpy(self->musicVolLabels[2], "50%");
    strcpy(self->musicVolLabels[3], "75%");
    strcpy(self->musicVolLabels[4], "100%");

    memcpy(self->sfxVolLabels, self->musicVolLabels, sizeof(self->sfxVolLabels));

    // Quality labels
    strcpy(self->qualityLabels[0], "HiFi 44100");
    strcpy(self->qualityLabels[1], "LoFi 11025");
    strcpy(self->qualityLabels[2], "WAV (TODO)");

    // Initialize clicks
    const char* volIds[] = { "musicVol0", "musicVol1", "musicVol2", "musicVol3", "musicVol4" };
    for (int i = 0; i < 5; i++) {
        initClaytonClick(&self->musicVolClicks[i], volIds[i]);
    }

    const char* sfxIds[] = { "sfxVol0", "sfxVol1", "sfxVol2", "sfxVol3", "sfxVol4" };
    for (int i = 0; i < 5; i++) {
        initClaytonClick(&self->sfxVolClicks[i], sfxIds[i]);
    }

    const char* qualIds[] = { "qualHifi", "qualLofi", "qualWav" };
    for (int i = 0; i < 3; i++) {
        initClaytonClick(&self->qualityClicks[i], qualIds[i]);
    }

    initClaytonClick(&self->nextSongClick, "nextSongClick");
    initClaytonClick(&self->closeClick, "soundSettingsClose");
}

inline void applySoundSettings(SoundSettings* self)
{
    if (!self->soundSystem) return;

    self->soundSystem->musicVolume = self->musicVolume;
    self->soundSystem->sfxVolume = self->sfxVolume;

    // Apply volume to modules
    if (self->soundSystem->musicModule) {
        xfm_module_set_volume(self->soundSystem->musicModule, self->musicVolume);
    }
    if (self->soundSystem->sfxModule) {
        xfm_module_set_volume(self->soundSystem->sfxModule, self->sfxVolume);
    }

    // Quality change - just store the setting (no restart in Emscripten)
    // The Web Audio API handles sample rate internally
    switch (self->quality) {
        case SoundSettings::QUALITY_HIFI:
            self->soundSystem->sampleRate = 44100;
            self->soundSystem->useWavPlayback = false;
            printf("Quality set to HiFi (setting stored, audio continues at browser rate)\n");
            break;
        case SoundSettings::QUALITY_LOFI:
            self->soundSystem->sampleRate = 11025;
            self->soundSystem->useWavPlayback = false;
            printf("Quality set to LoFi (setting stored, audio continues at browser rate)\n");
            break;
        case SoundSettings::QUALITY_WAV:
            self->soundSystem->sampleRate = 44100;
            self->soundSystem->useWavPlayback = true;
            printf("Quality set to WAV (TODO - setting stored)\n");
            break;
    }
}

inline bool processSoundSettingsEvent(SoundSettings* self, SDL_Event event)
{
    if (!self->activated) {
        return false;
    }

    bool mouseDown = event.type == SDL_MOUSEBUTTONDOWN;
    bool mouseUp = event.type == SDL_MOUSEBUTTONUP;

    if (!mouseDown && !mouseUp) {
        return false;
    }

    bool handled = false;

    // Music volume buttons
    for (int i = 0; i < 5; i++) {
        if (isClaytonClicked(&self->musicVolClicks[i], event)) {
            self->musicVolume = i * 0.25f;
            applySoundSettings(self);
            handled = true;
        }
    }

    // SFX volume buttons
    for (int i = 0; i < 5; i++) {
        if (isClaytonClicked(&self->sfxVolClicks[i], event)) {
            self->sfxVolume = i * 0.25f;
            applySoundSettings(self);
            handled = true;
        }
    }

    // Quality buttons
    for (int i = 0; i < 3; i++) {
        if (isClaytonClicked(&self->qualityClicks[i], event)) {
            self->quality = (SoundSettings::Quality)i;
            applySoundSettings(self);
            handled = true;
        }
    }

    // Next song button
    if (isClaytonClicked(&self->nextSongClick, event)) {
        if (self->soundSystem) {
            self->soundSystem->nextSong();
        }
        handled = true;
    }

    // Close button
    if (isClaytonClicked(&self->closeClick, event)) {
        self->activated = false;
        return true;
    }

    // If pointer is over the panel, consume the event (even if not on a button)
    // This prevents click-through to the game
    if (Clay_PointerOver(CLAY_ID("SoundSettingsContainer"))) {
        return true;
    }

    return handled;
}

inline void buildSoundSettingsClay(SoundSettings* self)
{
    if (!self->activated) {
        return;
    }

    // Font configs
    Clay_TextElementConfig labelFontCfg = {
        .textColor = {25, 25, 25, 255},
        .fontId = 0,
        .fontSize = (uint16_t)20,
    };

    Clay_TextElementConfig buttonFontCfg = {
        .textColor = {255, 255, 255, 255},
        .fontId = 2,
        .fontSize = (uint16_t)28,
    };

    Clay_TextElementConfig titleFontCfg = {
        .textColor = {255, 255, 255, 255},
        .fontId = 2,
        .fontSize = (uint16_t)36,
    };

    // Main container
    CLAY(
        CLAY_ID("SoundSettingsContainer"),
        {
            .layout = {
                .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_GROW()},
                .padding = {0, 0, 0, 0},
                .childAlignment = {CLAY_ALIGN_X_CENTER, CLAY_ALIGN_Y_CENTER},
                .layoutDirection = CLAY_LEFT_TO_RIGHT,
            },
        }
    ) {
        // Settings panel window
        CLAY(
            CLAY_ID("SoundSettingsWindow"),
            {
                .layout = {
                    .sizing = {CLAY_SIZING_PERCENT(0.8f), CLAY_SIZING_FIT()},
                    .padding = {20, 20, 20, 20},
                    .childGap = 15,
                    .layoutDirection = CLAY_TOP_TO_BOTTOM,
                },
                .backgroundColor = {40, 40, 60, 255},
                .cornerRadius = {15, 15, 15, 15},
            }
        ) {
            // Title bar
            CLAY(
                CLAY_ID("SoundSettingsTitle"),
                {
                    .layout = {
                        .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIT()},
                        .padding = {0, 0, 10, 0},
                        .childGap = 10,
                        .childAlignment = {CLAY_ALIGN_X_LEFT, CLAY_ALIGN_Y_CENTER},
                        .layoutDirection = CLAY_LEFT_TO_RIGHT,
                    },
                }
            ) {
                CLAY_TEXT(CLAY_STRING("Sound Settings"), CLAY_TEXT_CONFIG(titleFontCfg));

                // Close button (right side)
                CLAY(
                    self->closeClick.clayId,
                    {
                        .layout = {
                            .sizing = {CLAY_SIZING_FIXED(50), CLAY_SIZING_FIXED(50)},
                            .childAlignment = {CLAY_ALIGN_X_CENTER, CLAY_ALIGN_Y_CENTER},
                        },
                        .backgroundColor = {200, 50, 50, 255},
                        .cornerRadius = {10, 10, 10, 10},
                    }
                ) {
                    CLAY_TEXT(CLAY_STRING("X"), CLAY_TEXT_CONFIG(buttonFontCfg));
                }
            }

            // Music Volume Section
            CLAY(
                CLAY_ID("MusicVolSection"),
                {
                    .layout = {
                        .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIT()},
                        .padding = {10, 10, 10, 10},
                        .childGap = 10,
                        .layoutDirection = CLAY_TOP_TO_BOTTOM,
                    },
                    .backgroundColor = {60, 60, 80, 255},
                    .cornerRadius = {10, 10, 10, 10},
                }
            ) {
                CLAY_TEXT(CLAY_STRING("Music Volume"), CLAY_TEXT_CONFIG(labelFontCfg));

                // Volume buttons row
                CLAY(
                    CLAY_ID("MusicVolRow"),
                    {
                        .layout = {
                            .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIT()},
                            .childGap = 8,
                            .layoutDirection = CLAY_LEFT_TO_RIGHT,
                        },
                    }
                ) {
                    for (int i = 0; i < 5; i++) {
                        Clay_Color btnColor = (self->musicVolume == i * 0.25f) ?
                            Clay_Color{100, 200, 100, 255} : Clay_Color{80, 80, 120, 255};

                        CLAY(
                            self->musicVolClicks[i].clayId,
                            {
                                .layout = {
                                    .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIXED(50)},
                                    .childAlignment = {CLAY_ALIGN_X_CENTER, CLAY_ALIGN_Y_CENTER},
                                },
                                .backgroundColor = btnColor,
                                .cornerRadius = {8, 8, 8, 8},
                                .border = {
                                    .color = {150, 150, 200, 255},
                                    .width = CLAY_BORDER_ALL(2),
                                },
                            }
                        ) {
                            Clay_String label = {
                                .isStaticallyAllocated = false,
                                .length = (int)strlen(self->musicVolLabels[i]),
                                .chars = self->musicVolLabels[i],
                            };
                            CLAY_TEXT(label, CLAY_TEXT_CONFIG(buttonFontCfg));
                        }
                    }
                }
            }

            // SFX Volume Section
            CLAY(
                CLAY_ID("SfxVolSection"),
                {
                    .layout = {
                        .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIT()},
                        .padding = {10, 10, 10, 10},
                        .childGap = 10,
                        .layoutDirection = CLAY_TOP_TO_BOTTOM,
                    },
                    .backgroundColor = {60, 60, 80, 255},
                    .cornerRadius = {10, 10, 10, 10},
                }
            ) {
                CLAY_TEXT(CLAY_STRING("SFX Volume"), CLAY_TEXT_CONFIG(labelFontCfg));

                // Volume buttons row
                CLAY(
                    CLAY_ID("SfxVolRow"),
                    {
                        .layout = {
                            .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIT()},
                            .childGap = 8,
                            .layoutDirection = CLAY_LEFT_TO_RIGHT,
                        },
                    }
                ) {
                    for (int i = 0; i < 5; i++) {
                        Clay_Color btnColor = (self->sfxVolume == i * 0.25f) ?
                            Clay_Color{100, 200, 100, 255} : Clay_Color{80, 80, 120, 255};

                        CLAY(
                            self->sfxVolClicks[i].clayId,
                            {
                                .layout = {
                                    .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIXED(50)},
                                    .childAlignment = {CLAY_ALIGN_X_CENTER, CLAY_ALIGN_Y_CENTER},
                                },
                                .backgroundColor = btnColor,
                                .cornerRadius = {8, 8, 8, 8},
                                .border = {
                                    .color = {150, 150, 200, 255},
                                    .width = CLAY_BORDER_ALL(2),
                                },
                            }
                        ) {
                            Clay_String label = {
                                .isStaticallyAllocated = false,
                                .length = (int)strlen(self->sfxVolLabels[i]),
                                .chars = self->sfxVolLabels[i],
                            };
                            CLAY_TEXT(label, CLAY_TEXT_CONFIG(buttonFontCfg));
                        }
                    }
                }
            }

            // Quality Section
            CLAY(
                CLAY_ID("QualitySection"),
                {
                    .layout = {
                        .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIT()},
                        .padding = {10, 10, 10, 10},
                        .childGap = 10,
                        .layoutDirection = CLAY_TOP_TO_BOTTOM,
                    },
                    .backgroundColor = {60, 60, 80, 255},
                    .cornerRadius = {10, 10, 10, 10},
                }
            ) {
                CLAY_TEXT(CLAY_STRING("Audio Quality"), CLAY_TEXT_CONFIG(labelFontCfg));

                // Quality buttons row
                CLAY(
                    CLAY_ID("QualityRow"),
                    {
                        .layout = {
                            .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIT()},
                            .childGap = 8,
                            .layoutDirection = CLAY_LEFT_TO_RIGHT,
                        },
                    }
                ) {
                    for (int i = 0; i < 3; i++) {
                        Clay_Color btnColor = (self->quality == i) ?
                            Clay_Color{100, 200, 100, 255} : Clay_Color{80, 80, 120, 255};

                        CLAY(
                            self->qualityClicks[i].clayId,
                            {
                                .layout = {
                                    .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIXED(50)},
                                    .childAlignment = {CLAY_ALIGN_X_CENTER, CLAY_ALIGN_Y_CENTER},
                                },
                                .backgroundColor = btnColor,
                                .cornerRadius = {8, 8, 8, 8},
                                .border = {
                                    .color = {150, 150, 200, 255},
                                    .width = CLAY_BORDER_ALL(2),
                                },
                            }
                        ) {
                            Clay_String label = {
                                .isStaticallyAllocated = false,
                                .length = (int)strlen(self->qualityLabels[i]),
                                .chars = self->qualityLabels[i],
                            };
                            CLAY_TEXT(label, CLAY_TEXT_CONFIG(buttonFontCfg));
                        }
                    }
                }
            }

            // Action buttons row
            CLAY(
                CLAY_ID("ActionRow"),
                {
                    .layout = {
                        .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIT()},
                        .childGap = 10,
                        .layoutDirection = CLAY_LEFT_TO_RIGHT,
                    },
                }
            ) {
                // Next Song button
                CLAY(
                    self->nextSongClick.clayId,
                    {
                        .layout = {
                            .sizing = {CLAY_SIZING_GROW(), CLAY_SIZING_FIXED(60)},
                            .childAlignment = {CLAY_ALIGN_X_CENTER, CLAY_ALIGN_Y_CENTER},
                        },
                        .backgroundColor = {50, 100, 200, 255},
                        .cornerRadius = {10, 10, 10, 10},
                        .border = {
                            .color = {150, 150, 200, 255},
                            .width = CLAY_BORDER_ALL(2),
                        },
                    }
                ) {
                    CLAY_TEXT(CLAY_STRING("Next Song"), CLAY_TEXT_CONFIG(buttonFontCfg));
                }
            }
        }
    }
}

// Simplified song pattern (7 chars per channel, no effect columns)
const char* GameSoundSystem::SONG1 = R"(
256
C-3007F|C#30266|C-3017F|E-3017F|G-3017F
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|G-301..|B-301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#302..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
A-300..|C#402..|A-301..|C-301..|E-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
F-300..|C#302..|F-301..|A-301..|C-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
C-400..|C#302..|C-301..|E-301..|G-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
A-300..|C#302..|A-301..|C-301..|E-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
F-300..|C#302..|F-301..|A-301..|C-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|G-301..|B-301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
C-300..|C#302..|C-301..|E-301..|G-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
F-300..|C#302..|F-301..|A-301..|C-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
A-300..|C#302..|A-301..|C-301..|E-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|G-301..|B-301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
D-300..|C#302..|D-301..|F-301..|A-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|G-301..|B-301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
C-300..|C#302..|C-301..|E-301..|G-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#302..|C-301..|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
C-300..|C#302..|C-301..|E-301..|G-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|G-301..|B-301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
A-300..|C#302..|A-301..|C-301..|E-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
F-300..|C#302..|F-301..|A-301..|C-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
C-300..|C#302..|C-301..|E-301..|G-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
A-300..|C#302..|A-301..|C-301..|E-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
F-300..|C#302..|F-301..|A-301..|C-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|G-301..|B-301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
C-300..|C#302..|C-301..|E-301..|G-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
F-300..|C#302..|F-301..|A-301..|C-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
A-300..|C#302..|A-301..|C-301..|E-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|G-301..|B-301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
C-300..|C#302..|C-301..|D#301..|G-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
F-300..|C#302..|F-301..|G#301..|C-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|G-301..|B-301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|C#302..|C-301..|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|C#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......

)";

// Song 2 - Different chord progression
const char* GameSoundSystem::SONG2 = R"(
256
F-3007F|F#30266|F-3017F|A-3017F|C-3017F
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
D-300..|F#302..|D-301..|F-301..|A-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#302..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
G-300..|F#402..|G-301..|A#301..|D-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|F#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......

)";

// Song 3 - Minor key variation
const char* GameSoundSystem::SONG3 = R"(
256
A-3007F|A#30266|A-3017F|C-3017F|E-3017F
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
E-300..|A#302..|E-301..|G-301..|B-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#302..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
C-300..|A#402..|C-301..|D#301..|G-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|A#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......

)";

// Song 4 - Upbeat tempo variation
const char* GameSoundSystem::SONG4 = R"(
256
D-3007F|D#30266|D-3017F|F-3017F|A-3017F
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
A-300..|D#302..|A-301..|C-301..|E-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#302..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
F-300..|D#402..|F-301..|G#301..|C-301..
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|D#402..|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......
.......|.......|.......|.......|.......

)";