#pragma once
#include <xfm_song_dsl.h>

XFM_SONG_BEGIN(R"xfmname(Chest Ready Loop)xfmname")
XFM_TICK_RATE(60)
XFM_SPEED(3)
XFM_ROWS_PER_BEAT(1)
XFM_SCALE_ROOT(0)
XFM_SCALE_MODE(0)
XFM_LFO_ENABLED(1)
XFM_LFO_FREQUENCY(5)

XFM_PATTERN(R"xfmpattern(30
A-40044
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
OFF....
.......
.......
.......
.......
.......
)xfmpattern")

XFM_INSTRUMENTS(R"xfminstruments(
INST 00
NAME Chest Ready
COLOR CFE8FF
      ALG FB AMS FMS
PATCH   4  3   0   0
FM OP  TL AR DR SL SR RR SSG MUL DT RS AM
FM 1   24 18  4  8  5  8   0   2 -1  1  0
FM 2   31 12  3 10  4  8   0   3  1  1  0
FM 3   40 10  2 10  4  8   0   4  0  1  0
FM 4   10 16  3  8  5  9   0   1  0  0  0
ENDINST
)xfminstruments")

XFM_SONG_END()
