#!/usr/bin/env python3
import ast
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "tegel"
OUT_DIR = SRC_DIR / "generated"
OUT_FILE = OUT_DIR / "txl_generated.h"

LANG_FILES = {
    "en_us": SRC_DIR / "txl_en_us.h",
    "lt_lt": SRC_DIR / "txl_lt_lt.h",
    "jp_jp": SRC_DIR / "txl_jp_jp.h",
    "zh_cn": SRC_DIR / "txl_zh_cn.h",
}

ENTRY_RE = re.compile(r'^\s*(TXL_[A-Z0-9_]+)\s*=\s*"((?:[^"\\]|\\.)*)"\s*;\s*$')


def parse_lang_file(path: pathlib.Path):
    entries = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("//"):
            continue
        m = ENTRY_RE.match(line)
        if not m:
            raise ValueError(f"{path}: invalid txl DSL line: {raw_line}")
        key = m.group(1)
        value = ast.literal_eval(f'"{m.group(2)}"')
        entries.append((key, value))
    return entries


def dedupe_chars(values):
    seen = set()
    out = []
    for value in values:
        for ch in value:
            if ch not in seen:
                seen.add(ch)
                out.append(ch)
    return "".join(out)


def c_string_literal(value: str):
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def main():
    parsed = {name: parse_lang_file(path) for name, path in LANG_FILES.items()}
    key_order = [key for key, _ in parsed["en_us"]]
    for lang, entries in parsed.items():
        keys = [key for key, _ in entries]
        if keys != key_order:
            raise ValueError(f"{lang} keys do not match en_us order")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Generated by scripts/generate_txl.py")
    lines.append("")
    lines.append("enum TxlKey")
    lines.append("{")
    for key in key_order:
        lines.append(f"    {key},")
    lines.append("    TXL_KEY_COUNT")
    lines.append("};")
    lines.append("")

    for lang, entries in parsed.items():
        lines.append(f"static constexpr const char *g_txl_{lang}[TXL_KEY_COUNT] = {{")
        for _, value in entries:
            lines.append(f"    {c_string_literal(value)},")
        lines.append("};")
        lines.append("")

        chars = dedupe_chars([value for _, value in entries])
        lines.append(
            f"static constexpr const char *g_txl_chars_{lang} = {c_string_literal(chars)};"
        )
        lines.append("")

    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
